---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: postgres-connect-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.0.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  
  # Debezium PostgreSQL 커넥터 포함
  build:
    output:
      type: docker
      image: postgres-connect-debezium:latest
    plugins:
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/3.0.1.Final/debezium-connector-postgres-3.0.1.Final-plugin.tar.gz
  
  config:
    # Kafka Connect 설정
    group.id: postgres-connect-cluster
    offset.storage.topic: connect-cluster-offsets
    offset.storage.replication.factor: 1
    config.storage.topic: connect-cluster-configs
    config.storage.replication.factor: 1
    status.storage.topic: connect-cluster-status
    status.storage.replication.factor: 1
    
    # Converter 설정
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    
    # 내부 토픽 설정
    config.storage.topic: connect-cluster-configs
    offset.storage.topic: connect-cluster-offsets
    status.storage.topic: connect-cluster-status
    
  resources:
    requests:
      cpu: "0.5"
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi

---
# PostgreSQL Source Connector
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: postgres-source-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: postgres-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    # PostgreSQL 연결 정보
    database.hostname: "192.168.122.20"
    database.port: "5432"
    database.user: "myuser"
    database.password: "mypassword"
    database.dbname: "mydb"
    database.server.name: "postgres"
    
    # 스키마 및 테이블 설정
    table.include.list: "public.*"
    schema.include.list: "public"
    
    # Debezium 설정
    plugin.name: "pgoutput"
    slot.name: "debezium_slot"
    publication.name: "debezium_publication"
    
    # 메시지 변환 설정
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    
    # 초기 스냅샷 설정
    snapshot.mode: "initial"
    
    # 토픽 설정
    topic.prefix: "postgres"
    topic.creation.enable: true 