apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  # ✅ KRaft 모드를 활성화하는 어노테이션 추가
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    storage:
      type: ephemeral # 로컬 테스트용 임시 스토리지
    config:
      offsets.topic.replication.factor: 1 # 오프셋 토픽 복제 인수
      transaction.state.log.replication.factor: 1 # 트랜잭션 상태 로그 복제 인수
      transaction.state.log.min.isr: 1 # 트랜잭션 상태 로그 최소 ISR(In-Sync Replicas)
      default.replication.factor: 1 # 기본 복제 인수
      min.insync.replicas: 1 # 최소 ISR 수
  entityOperator:
    topicOperator: {}
    userOperator: {}
