apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kafka-setup

resources:
  - strimzi-rbac.yaml
  - kafka.yaml

namespace: kafka

commonLabels:
  app.kubernetes.io/name: kafka
  app.kubernetes.io/component: strimzi
  app.kubernetes.io/managed-by: argocd
