apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
spec:
  project: default
  sources:
    - chart: strimzi-kafka-operator
      repoURL: https://strimzi.io/charts
      targetRevision: 0.45.0
      helm:
        releaseName: strimzi
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/strimzi/develop/values.yaml
    - repoURL: "https://github.com/suhyun-guri/k8s_study"
      targetRevision: develop
      ref: values
  destination:
    namespace: kafka
    name: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
